valor = input('Digite qualquer valor (numérico, alfabético, alfanumérico): ')
print('O tipo primitivo é: {}'.format(type(valor)))
print('{} é um número? {}'.format(valor, valor.isnumeric()))
print('{} é um conjunto de letras? {}'.format(valor, valor.isalpha()))
print('{} é está em letras maiúsculas? {}'.format(valor, valor.isupper()))
print('{} é está em letras minúsculas? {}'.format(valor, valor.islower()))
print('{} é apenas um espaço vazio? {}'.format(valor, valor.isspace()))
print('{} pode ser imprimido na tela? {}'.format(valor, valor.isprintable()))
print('{} Está com a primeira letra maiúscula? {}'.format(valor, valor.istitle()))
